package co.edu.ucatolica.cl.ja.sgm.vista;

import javax.swing.JOptionPane;
/**
 *
 * @author oscar
 */
public class PanelAlbum extends javax.swing.JPanel {
    private final Principal principal;
    /**
     * Creates new form vista
     */
    public PanelAlbum(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabelAlbum = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelFechaGrabacion = new javax.swing.JLabel();
        jLabelFechaLanzamiento = new javax.swing.JLabel();
        jLabelDisquera = new javax.swing.JLabel();
        jLabelPortada = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldFechaGrabacion = new javax.swing.JTextField();
        jTextFieldFechaLanzamiento = new javax.swing.JTextField();
        jTextFieldDisquera = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPortada = new javax.swing.JTextArea();
        JButtonCrear = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelTituloVista = new javax.swing.JLabel();
        jComboBoxAlbunes = new javax.swing.JComboBox<>();
        jButtonCargar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCancerlar = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelAlbum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelAlbum.setText("Album");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelFechaGrabacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFechaGrabacion.setText("Fecha grabacion:");

        jLabelFechaLanzamiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFechaLanzamiento.setText("Fecha lanzamiento:");

        jLabelDisquera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDisquera.setText("Disquera:");

        jLabelPortada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPortada.setText("Portada:");

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jTextFieldFechaGrabacion.setToolTipText("");

        jTextAreaPortada.setColumns(20);
        jTextAreaPortada.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPortada);

        JButtonCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JButtonCrear.setText("Crear");
        JButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCrearActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setText("Limpiar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabelTituloVista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTituloVista.setText("Vista Previa");

        jComboBoxAlbunes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxAlbunes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja un album", "album 1", "album 2", "album 3" }));

        jButtonCargar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCargar.setText("Cargar");

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonModificar.setText("Modificar");

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonCancerlar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancerlar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonCrear)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDisquera)
                            .addComponent(jLabelPortada))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButtonCancerlar)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jTextFieldDisquera, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFechaLanzamiento)
                            .addComponent(jLabelFechaGrabacion)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabelTituloVista)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonModificar)
                                .addGap(132, 132, 132)
                                .addComponent(jButtonEliminar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxAlbunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jButtonCargar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabelAlbum)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelAlbum)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldFechaGrabacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFechaGrabacion))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelFechaLanzamiento)
                                    .addComponent(jTextFieldFechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelDisquera)
                                    .addComponent(jTextFieldDisquera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelPortada)
                                        .addGap(129, 129, 129))
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTituloVista)
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxAlbunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCargar))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonModificar)
                                .addComponent(jButtonEliminar))
                            .addComponent(jButtonCancelar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JButtonCrear)
                                .addComponent(jButtonCancerlar))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCrearActionPerformed
        crearAlbum();
    }//GEN-LAST:event_JButtonCrearActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCrear;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancerlar;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxAlbunes;
    private javax.swing.JLabel jLabelAlbum;
    private javax.swing.JLabel jLabelDisquera;
    private javax.swing.JLabel jLabelFechaGrabacion;
    private javax.swing.JLabel jLabelFechaLanzamiento;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPortada;
    private javax.swing.JLabel jLabelTituloVista;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaPortada;
    private javax.swing.JTextField jTextFieldDisquera;
    private javax.swing.JTextField jTextFieldFechaGrabacion;
    private javax.swing.JTextField jTextFieldFechaLanzamiento;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    private void limpiar(){
        this.jTextFieldNombre.setText("");
        this.jTextFieldFechaGrabacion.setText("");
        this.jTextFieldFechaLanzamiento.setText("");
        this.jTextFieldDisquera.setText("");
    }

    private boolean validar(){
        if(this.jTextFieldNombre.getText().equals("")){
            return false;
        }else if(this.jTextFieldFechaGrabacion.getText().equals("")){
            return false;
        }else if(this.jTextFieldFechaLanzamiento.equals("")){
            return false;
        }else if(this.jTextFieldDisquera.equals("")){
            return false;
        }else{
            try{
                int fechaGrabacion = Integer.parseInt(this.jTextFieldFechaGrabacion.getText());
                int fechaLanzamiento = Integer.parseInt(this.jTextFieldFechaLanzamiento.getText());
                return true;
            }catch(NullPointerException | NumberFormatException e ){
                return false;
            }
        }
    }

    private void crearAlbum(){
         if (validar()) {
            String nombre = this.jTextFieldNombre.getText();
            int fechaGrabacion = Integer.parseInt(this.jTextFieldFechaGrabacion.getText());
            int fechaLanzamiento = Integer.parseInt(this.jTextFieldFechaLanzamiento.getText());
            String disquera = this.jTextFieldDisquera.getText();
            boolean hecho = true; // no hay logica asi que esta incompleto el metodo
            if (hecho == true) {
                limpiar();
                JOptionPane.showMessageDialog(this, "Se creo el album", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se ingreso el album", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Algun dato no esta o no tiene el formato correcto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
}
