/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.cl.ja.sgm.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class PanelPerfil extends javax.swing.JPanel {

    private final Principal principal;
    private String[] datosUsuario = new String[4] ;

    /**
     * Creates new form PanelPerfil
     *
     * @param principal
     */
    public PanelPerfil(Principal principal) {
        this.principal = principal;
        this.datosUsuario=this.principal.obtenerDatosUsuario();
        initComponents();
        this.iniciarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jButtonCambiarContraseña = new javax.swing.JButton();
        jLabelHistorial = new javax.swing.JLabel();
        jScrollPaneHistorial = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonVolver = new javax.swing.JButton();
        jButtonModificarPerfil = new javax.swing.JButton();
        jLabelFoto = new javax.swing.JLabel();
        jButtonBorrarHistorial = new javax.swing.JButton();
        jButtonGuardarCambios = new javax.swing.JButton();
        jTextFieldNickname = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldMembresia = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();

        jTextField3.setText("jTextField1");

        jButtonCambiarContraseña.setText("Cambiar contraseña");
        jButtonCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarContraseñaActionPerformed(evt);
            }
        });

        jLabelHistorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHistorial.setText("HISTORIAL");

        jList1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneHistorial.setViewportView(jList1);

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/back_30x30.png"))); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonModificarPerfil.setText("Modificar perfil ");
        jButtonModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarPerfilActionPerformed(evt);
            }
        });

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/icono_2_150x155.jpg"))); // NOI18N

        jButtonBorrarHistorial.setText("Borrar historial");

        jButtonGuardarCambios.setText("Guardar cambios");
        jButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosActionPerformed(evt);
            }
        });

        jTextFieldNickname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNickname.setText("NICKNAME");
        jTextFieldNickname.setEnabled(false);

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setText("NOMBRE");
        jTextFieldNombre.setEnabled(false);

        jTextFieldMembresia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMembresia.setText("MEMBRESIA");
        jTextFieldMembresia.setEnabled(false);

        jTextFieldCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCorreo.setText("CORREO");
        jTextFieldCorreo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneHistorial)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarHistorial)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNickname)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldMembresia)
                    .addComponent(jTextFieldCorreo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHistorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarHistorial)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButtonModificarPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGuardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCambiarContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVolver)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarContraseñaActionPerformed
        // TODO add your handling code here:
      principal.irACambioContrasenia();
    }//GEN-LAST:event_jButtonCambiarContraseñaActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        principal.irAPrincipal();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarPerfilActionPerformed
        // TODO add your handling code here:
        this.bloquearCampos(true);
    }//GEN-LAST:event_jButtonModificarPerfilActionPerformed

    private void jButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosActionPerformed
        if (verificarCampos()) {
            String nombre = jTextFieldNombre.getText();
            String correo = jTextFieldCorreo.getText();
            principal.modificarCambiosUsuario(nombre,correo);
            this.bloquearCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Llene los campos", "Ayuda", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarCambiosActionPerformed

    private void iniciarCampos(){
        jTextFieldNickname.setText(datosUsuario[0]);
        jTextFieldNombre.setText(datosUsuario[1]);
        jTextFieldMembresia.setText(datosUsuario[2]);
        jTextFieldCorreo.setText(datosUsuario[3]);
                
        jTextFieldNickname.setEnabled(false);
        jTextFieldNombre.setEnabled(false);
        jTextFieldMembresia.setEnabled(false);
        jTextFieldCorreo.setEnabled(false);
    }
    private void bloquearCampos(boolean b){
        if(b){
            jTextFieldNickname.setEnabled(false);
            jTextFieldNombre.setEnabled(true);
            jTextFieldMembresia.setEnabled(true);
            jTextFieldCorreo.setEnabled(true);
        }else{
            jTextFieldNickname.setEnabled(false);
            jTextFieldNombre.setEnabled(false);
            jTextFieldMembresia.setEnabled(false);
            jTextFieldCorreo.setEnabled(false);    
        }
    }
    private boolean verificarCampos() {
        if (jTextFieldNickname.getText().equals("")) {
            return false;
        } else if (jTextFieldNombre.getText().equals("")) {
            return false;
        } else if (jTextFieldMembresia.getText().equals("")) {
            return false;
        } else if (jTextFieldCorreo.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarHistorial;
    private javax.swing.JButton jButtonCambiarContraseña;
    private javax.swing.JButton jButtonGuardarCambios;
    private javax.swing.JButton jButtonModificarPerfil;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelHistorial;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPaneHistorial;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldMembresia;
    private javax.swing.JTextField jTextFieldNickname;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
