package co.edu.ucatolica.cl.ja.sgm.vista;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sala3
 */
public class PerfilContrasena extends javax.swing.JPanel {

    /**
     * Creates new form PerfilContrasena
     */
    private final Principal principal;
    
    
        
    public PerfilContrasena(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordFieldRepetirNuevaContrasena = new javax.swing.JPasswordField();
        jPasswordNuevaContrasena = new javax.swing.JPasswordField();
        jTextFieldContrasenaAntigua = new javax.swing.JTextField();
        jLabelContrasenaVieja = new javax.swing.JLabel();
        jLabelNuevaContrasena = new javax.swing.JLabel();
        jLabelRepetirNuevaContrasena = new javax.swing.JLabel();
        jButtonGuardarContrasena = new javax.swing.JButton();
        jButtonCancelarCambiarContrasena = new javax.swing.JButton();
        TituloCambiarContraseña = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(319, 207));

        jLabelContrasenaVieja.setText("Constrasena Antigua:");

        jLabelNuevaContrasena.setText("Nueva Contraseña:");

        jLabelRepetirNuevaContrasena.setText("Repetir Contraseña:");

        jButtonGuardarContrasena.setText("Guardar");
        jButtonGuardarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarContrasenaActionPerformed(evt);
            }
        });

        jButtonCancelarCambiarContrasena.setText("Cancelar");
        jButtonCancelarCambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCambiarContrasenaActionPerformed(evt);
            }
        });

        TituloCambiarContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TituloCambiarContraseña.setText("Cambiar Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelContrasenaVieja))
                            .addComponent(jLabelNuevaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRepetirNuevaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldContrasenaAntigua, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jPasswordNuevaContrasena)
                            .addComponent(jPasswordFieldRepetirNuevaContrasena))
                        .addGap(189, 189, 189))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonGuardarContrasena)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonCancelarCambiarContrasena)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TituloCambiarContraseña)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(TituloCambiarContraseña)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContrasenaAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContrasenaVieja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldRepetirNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNuevaContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRepetirNuevaContrasena))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarContrasena)
                    .addComponent(jButtonCancelarCambiarContrasena))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarCambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCambiarContrasenaActionPerformed
        // TODO add your handling code here: 
        principal.cerrarVentanaContrasenia();
    }//GEN-LAST:event_jButtonCancelarCambiarContrasenaActionPerformed

    private void jButtonGuardarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarContrasenaActionPerformed
        // TODO add your handling code here:
        this.mensajes();
    }//GEN-LAST:event_jButtonGuardarContrasenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloCambiarContraseña;
    private javax.swing.JButton jButtonCancelarCambiarContrasena;
    private javax.swing.JButton jButtonGuardarContrasena;
    private javax.swing.JLabel jLabelContrasenaVieja;
    private javax.swing.JLabel jLabelNuevaContrasena;
    private javax.swing.JLabel jLabelRepetirNuevaContrasena;
    private javax.swing.JPasswordField jPasswordFieldRepetirNuevaContrasena;
    private javax.swing.JPasswordField jPasswordNuevaContrasena;
    private javax.swing.JTextField jTextFieldContrasenaAntigua;
    // End of variables declaration//GEN-END:variables
   
    private boolean validar() {
        if (jTextFieldContrasenaAntigua.getText().equals("")) {
            return false;
        } else if (jPasswordFieldRepetirNuevaContrasena.getText().equals(jPasswordNuevaContrasena.getText())) {
            return true;
        } else {
            return false;
        }
    }
    
    private void mensajes(){
        if(this.validar()){
            principal.cerrarVentanaContrasenia();
        }else{
             JOptionPane.showMessageDialog(this, "Las contraseñas son diferentes","Error contraseña",JOptionPane.INFORMATION_MESSAGE);
        }
    }


}
