/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucatolica.cl.ja.sgm.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author sala1
 */
public class RegistroPanel extends javax.swing.JPanel {

    private final Principal principal;

    /**
     * Creates new form RegistroPanel
     *
     * @param principal
     */
    public RegistroPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelregistro = new javax.swing.JLabel();
        jLabelnickname = new javax.swing.JLabel();
        jTextFieldusuario = new javax.swing.JTextField();
        jLabelcorreo = new javax.swing.JLabel();
        jTextFieldcorreo = new javax.swing.JTextField();
        jLabelcontraseña = new javax.swing.JLabel();
        jPasswordconfirma = new javax.swing.JPasswordField();
        jLabelmembresia = new javax.swing.JLabel();
        jButtonregistro = new javax.swing.JButton();
        jButtoncancelar = new javax.swing.JButton();
        jLabelfoto = new javax.swing.JLabel();
        jComboBoxmembresia = new javax.swing.JComboBox<>();
        jLabelnombre = new javax.swing.JLabel();
        jTextFieldnombre = new javax.swing.JTextField();
        jButtonimportar = new javax.swing.JButton();
        jLabelconfirma = new javax.swing.JLabel();
        jPasswordcontraseña = new javax.swing.JPasswordField();
        jButtonayuda = new javax.swing.JButton();
        jButtonregistro1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setForeground(new java.awt.Color(153, 153, 153));

        jLabelregistro.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabelregistro.setText("REGISTRO ");

        jLabelnickname.setText("NickName:");

        jLabelcorreo.setText("Correo:");

        jLabelcontraseña.setText("Contraseña");

        jPasswordconfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordconfirmaActionPerformed(evt);
            }
        });

        jLabelmembresia.setText("Tipo de Membresia");

        jButtonregistro.setText("Registro");
        jButtonregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistroActionPerformed(evt);
            }
        });

        jButtoncancelar.setText("Cancelar");
        jButtoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelarActionPerformed(evt);
            }
        });

        jLabelfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/imgprofile2.png"))); // NOI18N

        jComboBoxmembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------", "Clasica", "Platino", "Oro" }));

        jLabelnombre.setText("Nombres y Apellidos:");

        jButtonimportar.setText("Cargar imagen");
        jButtonimportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonimportarActionPerformed(evt);
            }
        });

        jLabelconfirma.setText("Confirma su contraseña:");

        jPasswordcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordcontraseñaActionPerformed(evt);
            }
        });

        jButtonayuda.setText("Ayuda");
        jButtonayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonayudaActionPerformed(evt);
            }
        });

        jButtonregistro1.setText("Limpiar");
        jButtonregistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelfoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelcorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelnickname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelmembresia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelconfirma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelcontraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldusuario)
                            .addComponent(jTextFieldcorreo)
                            .addComponent(jComboBoxmembresia, 0, 194, Short.MAX_VALUE)
                            .addComponent(jPasswordcontraseña)
                            .addComponent(jPasswordconfirma)
                            .addComponent(jTextFieldnombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonregistro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonregistro1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtoncancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonayuda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonimportar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelregistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelregistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelfoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonimportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnombre)
                    .addComponent(jTextFieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnickname)
                    .addComponent(jTextFieldusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcorreo)
                    .addComponent(jTextFieldcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmembresia)
                    .addComponent(jComboBoxmembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcontraseña)
                    .addComponent(jPasswordcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelconfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordconfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonregistro)
                    .addComponent(jButtonregistro1)
                    .addComponent(jButtoncancelar)
                    .addComponent(jButtonayuda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistroActionPerformed
        registrar();
    }//GEN-LAST:event_jButtonregistroActionPerformed

    private void jButtonregistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonregistro1ActionPerformed

    private void jButtonimportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonimportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonimportarActionPerformed

    private void jPasswordcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordcontraseñaActionPerformed

    private void jPasswordconfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordconfirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordconfirmaActionPerformed

    private void jButtoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelarActionPerformed
        principal.irAInicioDeSesion();
    }//GEN-LAST:event_jButtoncancelarActionPerformed

    private void jButtonayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonayudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonayuda;
    private javax.swing.JButton jButtoncancelar;
    private javax.swing.JButton jButtonimportar;
    private javax.swing.JButton jButtonregistro;
    private javax.swing.JButton jButtonregistro1;
    private javax.swing.JComboBox<String> jComboBoxmembresia;
    private javax.swing.JLabel jLabelconfirma;
    private javax.swing.JLabel jLabelcontraseña;
    private javax.swing.JLabel jLabelcorreo;
    private javax.swing.JLabel jLabelfoto;
    private javax.swing.JLabel jLabelmembresia;
    private javax.swing.JLabel jLabelnickname;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabelregistro;
    private javax.swing.JPasswordField jPasswordconfirma;
    private javax.swing.JPasswordField jPasswordcontraseña;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldcorreo;
    private javax.swing.JTextField jTextFieldnombre;
    private javax.swing.JTextField jTextFieldusuario;
    // End of variables declaration//GEN-END:variables

    public void registrar() {
        if (validar()) {
            JOptionPane.showMessageDialog(this, "ingreso correcto", "", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "espacios no llenados", "", JOptionPane.WARNING_MESSAGE);
        }
    }

    public boolean validar() {
        if (this.jTextFieldnombre.getText().equals("")) {
            return false;
        } else if (this.jTextFieldusuario.getText().equals("")) {
            return false;
        } else if (this.jTextFieldnombre.getText().equals("")) {
            return false;
        } else if (this.jPasswordconfirma.getText().equals("")) {
            return false;
        } else if (this.jPasswordcontraseña.getText().equals("")) {
            return false;
        }
        return true;
    }

}
